CREATE TABLE F_Type (
    F_Type_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
    F_Type_Name VARCHAR NOT NULL
);

CREATE TABLE F_Maker (
    F_Maker_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    F_Maker_Name VARCHAR NOT NULL
);

CREATE TABLE F_Set (
    F_Set_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    F_Set_Name VARCHAR NOT NULL
);

CREATE TABLE F_Material (
    F_Material_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    F_Material_Name VARCHAR NOT NULL
);

CREATE TABLE F_Entity (
    F_Entity_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    F_Entity_Price NUMBER NOT NULL,
    F_Entity_Quantity NUMBER NOT NULL,
    F_Entity_Height NUMBER NOT NULL,
    F_Entity_Width NUMBER NOT NULL,
    F_Entity_Length NUMBER NOT NULL,
    F_Entity_Color VARCHAR NOT NULL,
    F_Type_ID INTEGER NOT NULL,
  	F_Maker_ID INTEGER NOT NULL,  
  	F_Material_ID INTEGER NOT NULL,	
  	FOREIGN KEY (F_Type_ID) REFERENCES F_Type(F_Type_ID) ON DELETE CASCADE,
    FOREIGN KEY (F_Maker_ID) REFERENCES F_Maker(F_Maker_ID) ON DELETE CASCADE,
    FOREIGN KEY (F_Material_ID) REFERENCES F_Material(F_Material_ID) ON DELETE CASCADE
);

CREATE TABLE F_Sales (
    F_Sales_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    F_Sales_Quantity INTEGER NOT NULL,
    F_Entity_ID INTEGER NOT NULL,
    F_Entity_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (F_Entity_ID) REFERENCES F_Entity(F_Entity_ID) ON DELETE CASCADE
);

CREATE TABLE F_Sets (
    F_Set_ID INTEGER NOT NULL,
    F_Entity_ID INTEGER NOT NULL,
    FOREIGN KEY (F_Entity_ID) REFERENCES F_Entity(F_Entity_ID) ON DELETE CASCADE,
    FOREIGN KEY (F_Set_ID) REFERENCES F_Set(F_Set_ID) ON DELETE CASCADE


);